FROM node:8
WORKDIR /home/imtu-simple
COPY package*.json ./
COPY file.json qwetqwwetqwtqtweqtqwetqwtqt.json
RUN echo -e "NODE_ORACLEDB_USER=\$NODE_ORACLEDB_CREDS_USR\n\
NODE_ORACLEDB_PASSWORD=\$NODE_ORACLEDB_CREDS_PSW\n\
DB_HOST=\$DB_HOST\n\
DB_HOST_PORT=\$DB_HOST_PORT\n\
DB_SERVICE_NAME=\$DB_SERVICE_NAME\n\
EMAIL_USER=\$EMAIL_SENDER_USR \n\
EMAIL_PASSWORD=\$EMAIL_SENDER_PSW\n\
EMAIL_RECEIVER=\$EMAIL_RECEIVER\n\
TABLE_BALANCE=debit.EXPORT_TABLE\n\
TABLE_BALANCE_INCREASE=DEBIT.IMTU_BALANCE_INCREASE\n\
TABLE_WALLET_INFO=IMTU_WALLET_INFO\n\
VIEW_TRANSVIEW=TRANSVIEW\n\
CHECK_INTERVAL=600000" > .env

